tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "as-tree"
brew "python@3.10", link: true
brew "azure-cli"
brew "bat"
brew "clang-format"
brew "coreutils"
brew "deno"
brew "fd"
brew "fnm"
brew "gh"
brew "git"
brew "gnupg"
brew "go"
brew "jq"
brew "loc"
brew "mas"
brew "neofetch"
brew "prettier"
brew "python@3.9", link: false
brew "rclone"
brew "restic"
brew "ripgrep"
brew "rsync"
brew "sd"
brew "shfmt"
brew "socat"
brew "speedtest-cli"
brew "tokei"
brew "topgrade"
brew "tree"
brew "typescript"
brew "wget"
brew "yarn"
cask "1password"
cask "appcleaner"
cask "brave-browser"
cask "daisydisk"
cask "discord"
cask "docker"
cask "dotnet-sdk"
cask "firefox"
cask "gitahead"
cask "istat-menus"
cask "iterm2"
cask "kap"
cask "microsoft-edge"
cask "microsoft-teams"
cask "monodraw"
cask "mos"
cask "obs"
cask "powershell"
cask "slack"
cask "spotify"
cask "visual-studio-code"
mas "Amphetamine", id: 937984704
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Microsoft Excel", id: 462058435
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "The Unarchiver", id: 425424353
mas "Todoist", id: 585829637
