tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "socsieng/tap"
tap "oven-sh/bun"
brew "as-tree"
brew "python@3.10"
brew "azure-cli"
brew "bat"
brew "bottom"
brew "clang-format"
brew "coreutils"
brew "cowsay"
brew "dos2unix"
brew "fd"
brew "fnm"
brew "gh"
brew "git"
brew "gnupg"
brew "go"
brew "imagemagick"
brew "jq"
brew "make"
brew "mas"
brew "miniserve"
brew "neofetch"
brew "r"
brew "rclone"
brew "restic"
brew "ripgrep"
brew "rsync"
brew "sd"
brew "shfmt"
brew "speedtest-cli"
brew "swiftformat"
brew "tokei"
brew "tree"
brew "typescript"
brew "vim"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "socsieng/tap/sendkeys"
brew "oven-sh/bun/bun"
cask "appcleaner"
cask "dotnet-sdk"
cask "firefox"
cask "iterm2"
cask "kap"
cask "microsoft-edge"
cask "microsoft-remote-desktop"
cask "microsoft-teams"
cask "monodraw"
cask "obs"
cask "obsidian"
cask "optimus-player"
cask "powershell"
cask "spotify"
cask "visual-studio-code"
cask "zoom"
mas "Amphetamine", id: 937984704
mas "Compressor", id: 424390742
mas "Final Cut Pro", id: 424389933
mas "ISO8601", id: 1505772375
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Microsoft Excel", id: 462058435
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator Pro", id: 1289583905
mas "The Unarchiver", id: 425424353
