tap "azure/functions"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "socsieng/tap"
tap "oven-sh/bun"
brew "as-tree"
brew "python@3.10"
brew "azure-cli"
brew "bat"
brew "bottom"
brew "clang-format"
brew "gnutls"
brew "colima"
brew "coreutils"
brew "cowsay"
brew "docker"
brew "docker-compose"
brew "fd"
brew "fnm"
brew "gh"
brew "git"
brew "gnupg"
brew "go"
brew "imagemagick"
brew "make"
brew "mas"
brew "miniserve"
brew "neofetch"
brew "python@3.11"
brew "rclone"
brew "restic"
brew "ripgrep"
brew "rsync"
brew "sd"
brew "shfmt"
brew "speedtest-cli"
brew "swiftformat"
brew "tokei"
brew "tree"
brew "typescript"
brew "vercel-cli"
brew "vim"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "azure/functions/azure-functions-core-tools@4"
brew "socsieng/tap/sendkeys"
brew "oven-sh/bun/bun"
cask "1password"
cask "appcleaner"
cask "arc"
cask "brave-browser"
cask "daisydisk"
cask "discord"
cask "dotnet-sdk"
cask "firefox"
cask "google-chrome"
cask "istat-menus"
cask "iterm2"
cask "kap"
cask "metaz"
cask "monodraw"
cask "notion"
cask "obs"
cask "obsidian"
cask "optimus-player"
cask "powershell"
cask "signal"
cask "sketch"
cask "spotify"
cask "steam"
cask "transmission"
cask "visual-studio-code"
cask "zoom"
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Affinity Publisher", id: 881418622
mas "Amphetamine", id: 937984704
mas "Compressor", id: 424390742
mas "Debit & Credit", id: 882637653
mas "Final Cut Pro", id: 424389933
mas "Flighty", id: 1358823008
mas "GarageBand", id: 682658836
mas "Goodnotes", id: 1444383602
mas "Infuse", id: 1136220934
mas "Keynote", id: 409183694
mas "MacFamilyTree 10", id: 1567970985
mas "Magnet", id: 441258766
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Motion", id: 434290957
mas "Notability", id: 360593530
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Parcel", id: 639968404
mas "Photomator", id: 1444636541
mas "Pixelmator Pro", id: 1289583905
mas "RAW Power", id: 1157116444
mas "Streaks", id: 963034692
mas "TestFlight", id: 899247664
mas "The Unarchiver", id: 425424353
mas "Things", id: 904280696
mas "Todoist", id: 585829637
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
